name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: ${{matrix.os}} ${{matrix.compiler}} ${{matrix.build_type}}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compiler: [msvc]
        generator: [Ninja]
        preset: [debug, release, distribution]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{matrix.compiler}}
          vcvarsall: ${{runner.os == 'Windows'}}
          cmake: true
          ninja: true
          vcpkg: true
          clangtidy: "20.1.7"

      - name: Configure CMake
        run: cmake . --preset ${{matrix.preset}} -DCMAKE_TOOLCHAIN_FILE='~/vcpkg/scripts/buildsystems/vcpkg.cmake' -DCMAKE_CXX_CLANG_TIDY='clang-tidy;-style=file'

      - name: Build
        run: cmake --build --preset ${{matrix.preset}}

      - name: Test
        if: ${{preset != 'distribution'}}
        run: ctest --preset ${{matrix.preset}}
