name: ci
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    name: ${{matrix.os.name}} ${{matrix.compiler.name}} ${{matrix.build-type}}
    runs-on: ${{matrix.os.name}}
    env:
      CMAKE_BINARY_DIR: Build
      CMAKE_TOOLCHAIN_FILE: ~/vcpkg/scripts/buildsystems/vcpkg.cmake
      CMAKE_CXX_COMPILER: ${{matrix.compiler.path}}
      CMAKE_BUILD_TYPE: ${{matrix.build-type}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: windows-latest
            preset: windows
        generator:
          - Ninja
        build-type:
          - Debug
          - Release
        compiler:
          - name: msvc
            path: cl
    steps:
      - uses: actions/checkout@v4
      - name: Setup C++
        uses: aminya/setup-cpp@v1.7.1
        with:
          compiler: ${{matrix.compiler.name}}
          vcvarsall: ${{runner.os == 'Windows'}}
          cmake: "4.0.3"
          ninja: "1.13.0"
          vcpkg: true
          clangtidy: "20.1.7"
      - name: Install NSIS
        if: ${{runner.os == 'Windows'}}
        uses: repolevedavaj/install-nsis@v1.0.3
        with:
          nsis-version: "3.11"
      - name: Run CMake workflow
        run: cmake --workflow --preset ${{matrix.os.preset}}
  format:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "20"
          include-regex: ^.*/(Applications|Source|Tests)/.*\.(hpp|cpp)$
